[tool.poetry]
name = "nonebot-plugin-bili-share-keeper"
version = "0.0.1"
description = "记录b站视频链接分享，并提示多次分享"
authors = ["qianqiuzy <qianqiuzy@gmail.com>"]
readme = "README.md"
repository = "https://github.com/qianqiuzy/nonebot-plugin-bili-share-keeper"
keywords = ["nonebot", "nonebot2", "plugin"]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
httpx = ">=0.27.0"
nonebot2 = "^2.3.0"
nonebot-adapter-onebot = ">=2.0.0-beta.1"
pydantic = ">=1.10.0,<3.0.0"
redis = ">=5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "RUF"
]
ignore = [
    "E402",   # module-import-not-at-top-of-file
    "UP006",  # non-pep585-annotation
    "UP035",  # deprecated-import
    "UP037",  # quoted-annotation
    "RUF001", # ambiguous-unicode-character-string
    "RUF002", # ambiguous-unicode-character-docstring
    "RUF003", # ambiguous-unicode-character-comment
]